;   A tile map representa as tiles do mapa
;em uma grid de 20 x 13, para ser utilizada com sprites
;2 X 2.
tile_map : var #260
	static tile_map + #0, #'A'
	static tile_map + #1, #'A'
	static tile_map + #2, #'A'
	static tile_map + #3, #'A'
	static tile_map + #4, #'A'
	static tile_map + #5, #'A'
	static tile_map + #6, #'A'
	static tile_map + #7, #'A'
	static tile_map + #8, #'A'
	static tile_map + #9, #'A'
	static tile_map + #10, #'A'
	static tile_map + #11, #'A'
	static tile_map + #12, #'A'
	static tile_map + #13, #'A'
	static tile_map + #14, #'A'
	static tile_map + #15, #'A'
	static tile_map + #16, #'A'
	static tile_map + #17, #'A'
	static tile_map + #18, #'A'
	static tile_map + #19, #'A'
	static tile_map + #20, #'A'
	static tile_map + #21, #0
	static tile_map + #22, #0
	static tile_map + #23, #0
	static tile_map + #24, #0
	static tile_map + #25, #0
	static tile_map + #26, #'B'
	static tile_map + #27, #'B'
	static tile_map + #28, #'B'
	static tile_map + #29, #'B'
	static tile_map + #30, #'A'
	static tile_map + #31, #0
	static tile_map + #32, #0
	static tile_map + #33, #0
	static tile_map + #34, #'A'
	static tile_map + #35, #0
	static tile_map + #36, #0
	static tile_map + #37, #0
	static tile_map + #38, #0
	static tile_map + #39, #'A'
	static tile_map + #40, #'A'
	static tile_map + #41, #0
	static tile_map + #42, #0
	static tile_map + #43, #0
	static tile_map + #44, #0
	static tile_map + #45, #0
	static tile_map + #46, #'B'
	static tile_map + #47, #'B'
	static tile_map + #48, #'A'
	static tile_map + #49, #'B'
	static tile_map + #50, #0
	static tile_map + #51, #0
	static tile_map + #52, #'A'
	static tile_map + #53, #0
	static tile_map + #54, #0
	static tile_map + #55, #0
	static tile_map + #56, #'A'
	static tile_map + #57, #0
	static tile_map + #58, #0
	static tile_map + #59, #'A'
	static tile_map + #60, #'A'
	static tile_map + #61, #0
	static tile_map + #62, #0
	static tile_map + #63, #0
	static tile_map + #64, #0
	static tile_map + #65, #0
	static tile_map + #66, #'A'
	static tile_map + #67, #'B'
	static tile_map + #68, #'B'
	static tile_map + #69, #'B'
	static tile_map + #70, #0
	static tile_map + #71, #0
	static tile_map + #72, #0
	static tile_map + #73, #0
	static tile_map + #74, #'B'
	static tile_map + #75, #'B'
	static tile_map + #76, #'B'
	static tile_map + #77, #'B'
	static tile_map + #78, #'B'
	static tile_map + #79, #'A'
	static tile_map + #80, #'A'
	static tile_map + #81, #0
	static tile_map + #82, #0
	static tile_map + #83, #0
	static tile_map + #84, #0
	static tile_map + #85, #0
	static tile_map + #86, #'A'
	static tile_map + #87, #'B'
	static tile_map + #88, #'B'
	static tile_map + #89, #'A'
	static tile_map + #90, #'B'
	static tile_map + #91, #'B'
	static tile_map + #92, #0
	static tile_map + #93, #'A'
	static tile_map + #94, #'B'
	static tile_map + #95, #'B'
	static tile_map + #96, #'B'
	static tile_map + #97, #'B'
	static tile_map + #98, #'B'
	static tile_map + #99, #'A'
	static tile_map + #100, #'A'
	static tile_map + #101, #'B'
	static tile_map + #102, #'B'
	static tile_map + #103, #'A'
	static tile_map + #104, #'A'
	static tile_map + #105, #'A'
	static tile_map + #106, #'A'
	static tile_map + #107, #0
	static tile_map + #108, #0
	static tile_map + #109, #'A'
	static tile_map + #110, #'B'
	static tile_map + #111, #'B'
	static tile_map + #112, #0
	static tile_map + #113, #0
	static tile_map + #114, #'B'
	static tile_map + #115, #'A'
	static tile_map + #116, #'B'
	static tile_map + #117, #'A'
	static tile_map + #118, #'B'
	static tile_map + #119, #'A'
	static tile_map + #120, #'A'
	static tile_map + #121, #'B'
	static tile_map + #122, #'B'
	static tile_map + #123, #'B'
	static tile_map + #124, #'B'
	static tile_map + #125, #'B'
	static tile_map + #126, #0
	static tile_map + #127, #'B'
	static tile_map + #128, #'B'
	static tile_map + #129, #'A'
	static tile_map + #130, #'B'
	static tile_map + #131, #'B'
	static tile_map + #132, #0
	static tile_map + #133, #0
	static tile_map + #134, #'B'
	static tile_map + #135, #0
	static tile_map + #136, #'B'
	static tile_map + #137, #'B'
	static tile_map + #138, #'B'
	static tile_map + #139, #'A'
	static tile_map + #140, #'A'
	static tile_map + #141, #'B'
	static tile_map + #142, #'A'
	static tile_map + #143, #'B'
	static tile_map + #144, #'A'
	static tile_map + #145, #'B'
	static tile_map + #146, #0
	static tile_map + #147, #'B'
	static tile_map + #148, #'B'
	static tile_map + #149, #'A'
	static tile_map + #150, #0
	static tile_map + #151, #0
	static tile_map + #152, #'A'
	static tile_map + #153, #'A'
	static tile_map + #154, #'A'
	static tile_map + #155, #'A'
	static tile_map + #156, #'B'
	static tile_map + #157, #'B'
	static tile_map + #158, #'B'
	static tile_map + #159, #'A'
	static tile_map + #160, #'A'
	static tile_map + #161, #'B'
	static tile_map + #162, #'B'
	static tile_map + #163, #'B'
	static tile_map + #164, #'B'
	static tile_map + #165, #'B'
	static tile_map + #166, #0
	static tile_map + #167, #'B'
	static tile_map + #168, #'B'
	static tile_map + #169, #'A'
	static tile_map + #170, #0
	static tile_map + #171, #0
	static tile_map + #172, #'A'
	static tile_map + #173, #0
	static tile_map + #174, #0
	static tile_map + #175, #0
	static tile_map + #176, #0
	static tile_map + #177, #0
	static tile_map + #178, #0
	static tile_map + #179, #'A'
	static tile_map + #180, #'A'
	static tile_map + #181, #'B'
	static tile_map + #182, #'A'
	static tile_map + #183, #'B'
	static tile_map + #184, #'A'
	static tile_map + #185, #'B'
	static tile_map + #186, #0
	static tile_map + #187, #'B'
	static tile_map + #188, #'B'
	static tile_map + #189, #'A'
	static tile_map + #190, #'B'
	static tile_map + #191, #'B'
	static tile_map + #192, #'A'
	static tile_map + #193, #0
	static tile_map + #194, #'B'
	static tile_map + #195, #0
	static tile_map + #196, #0
	static tile_map + #197, #0
	static tile_map + #198, #0
	static tile_map + #199, #'A'
	static tile_map + #200, #'A'
	static tile_map + #201, #'B'
	static tile_map + #202, #'B'
	static tile_map + #203, #'B'
	static tile_map + #204, #'B'
	static tile_map + #205, #'B'
	static tile_map + #206, #'A'
	static tile_map + #207, #0
	static tile_map + #208, #0
	static tile_map + #209, #0
	static tile_map + #210, #0
	static tile_map + #211, #0
	static tile_map + #212, #'B'
	static tile_map + #213, #0
	static tile_map + #214, #0
	static tile_map + #215, #0
	static tile_map + #216, #0
	static tile_map + #217, #0
	static tile_map + #218, #0
	static tile_map + #219, #'A'
	static tile_map + #220, #'A'
	static tile_map + #221, #0
	static tile_map + #222, #0
	static tile_map + #223, #0
	static tile_map + #224, #0
	static tile_map + #225, #0
	static tile_map + #226, #0
	static tile_map + #227, #0
	static tile_map + #228, #0
	static tile_map + #229, #'A'
	static tile_map + #230, #0
	static tile_map + #231, #0
	static tile_map + #232, #'B'
	static tile_map + #233, #0
	static tile_map + #234, #0
	static tile_map + #235, #0
	static tile_map + #236, #0
	static tile_map + #237, #0
	static tile_map + #238, #0
	static tile_map + #239, #'A'
	static tile_map + #240, #'A'
	static tile_map + #241, #'A'
	static tile_map + #242, #'A'
	static tile_map + #243, #'A'
	static tile_map + #244, #'A'
	static tile_map + #245, #'A'
	static tile_map + #246, #'A'
	static tile_map + #247, #'A'
	static tile_map + #248, #'A'
	static tile_map + #249, #'A'
	static tile_map + #250, #'A'
	static tile_map + #251, #'A'
	static tile_map + #252, #'A'
	static tile_map + #253, #'A'
	static tile_map + #254, #'A'
	static tile_map + #255, #'A'
	static tile_map + #256, #'A'
	static tile_map + #257, #'A'
	static tile_map + #258, #'A'
	static tile_map + #259, #'A'

; Posicao do player e 1 player 2, em que o offset 0 eh o x e o offset 1 eh o y
player_one_ini_pos : var #2
	static player_one_ini_pos + #0, #2
	static player_one_ini_pos + #1, #2
player_two_ini_pos : var #2
	static player_two_ini_pos + #0, #16
	static player_two_ini_pos + #1, #10


tile_map_og : var #260
	static tile_map_og + #0, #'A'
	static tile_map_og + #1, #'A'
	static tile_map_og + #2, #'A'
	static tile_map_og + #3, #'A'
	static tile_map_og + #4, #'A'
	static tile_map_og + #5, #'A'
	static tile_map_og + #6, #'A'
	static tile_map_og + #7, #'A'
	static tile_map_og + #8, #'A'
	static tile_map_og + #9, #'A'
	static tile_map_og + #10, #'A'
	static tile_map_og + #11, #'A'
	static tile_map_og + #12, #'A'
	static tile_map_og + #13, #'A'
	static tile_map_og + #14, #'A'
	static tile_map_og + #15, #'A'
	static tile_map_og + #16, #'A'
	static tile_map_og + #17, #'A'
	static tile_map_og + #18, #'A'
	static tile_map_og + #19, #'A'
	static tile_map_og + #20, #'A'
	static tile_map_og + #21, #0
	static tile_map_og + #22, #0
	static tile_map_og + #23, #0
	static tile_map_og + #24, #0
	static tile_map_og + #25, #0
	static tile_map_og + #26, #'B'
	static tile_map_og + #27, #'B'
	static tile_map_og + #28, #'B'
	static tile_map_og + #29, #'B'
	static tile_map_og + #30, #'A'
	static tile_map_og + #31, #0
	static tile_map_og + #32, #0
	static tile_map_og + #33, #0
	static tile_map_og + #34, #'A'
	static tile_map_og + #35, #0
	static tile_map_og + #36, #0
	static tile_map_og + #37, #0
	static tile_map_og + #38, #0
	static tile_map_og + #39, #'A'
	static tile_map_og + #40, #'A'
	static tile_map_og + #41, #0
	static tile_map_og + #42, #0
	static tile_map_og + #43, #0
	static tile_map_og + #44, #0
	static tile_map_og + #45, #0
	static tile_map_og + #46, #'B'
	static tile_map_og + #47, #'B'
	static tile_map_og + #48, #'A'
	static tile_map_og + #49, #'B'
	static tile_map_og + #50, #0
	static tile_map_og + #51, #0
	static tile_map_og + #52, #'A'
	static tile_map_og + #53, #0
	static tile_map_og + #54, #0
	static tile_map_og + #55, #0
	static tile_map_og + #56, #'A'
	static tile_map_og + #57, #0
	static tile_map_og + #58, #0
	static tile_map_og + #59, #'A'
	static tile_map_og + #60, #'A'
	static tile_map_og + #61, #0
	static tile_map_og + #62, #0
	static tile_map_og + #63, #0
	static tile_map_og + #64, #0
	static tile_map_og + #65, #0
	static tile_map_og + #66, #'A'
	static tile_map_og + #67, #'B'
	static tile_map_og + #68, #'B'
	static tile_map_og + #69, #'B'
	static tile_map_og + #70, #0
	static tile_map_og + #71, #0
	static tile_map_og + #72, #0
	static tile_map_og + #73, #0
	static tile_map_og + #74, #'B'
	static tile_map_og + #75, #'B'
	static tile_map_og + #76, #'B'
	static tile_map_og + #77, #'B'
	static tile_map_og + #78, #'B'
	static tile_map_og + #79, #'A'
	static tile_map_og + #80, #'A'
	static tile_map_og + #81, #0
	static tile_map_og + #82, #0
	static tile_map_og + #83, #0
	static tile_map_og + #84, #0
	static tile_map_og + #85, #0
	static tile_map_og + #86, #'A'
	static tile_map_og + #87, #'B'
	static tile_map_og + #88, #'B'
	static tile_map_og + #89, #'A'
	static tile_map_og + #90, #'B'
	static tile_map_og + #91, #'B'
	static tile_map_og + #92, #0
	static tile_map_og + #93, #'A'
	static tile_map_og + #94, #'B'
	static tile_map_og + #95, #'B'
	static tile_map_og + #96, #'B'
	static tile_map_og + #97, #'B'
	static tile_map_og + #98, #'B'
	static tile_map_og + #99, #'A'
	static tile_map_og + #100, #'A'
	static tile_map_og + #101, #'B'
	static tile_map_og + #102, #'B'
	static tile_map_og + #103, #'A'
	static tile_map_og + #104, #'A'
	static tile_map_og + #105, #'A'
	static tile_map_og + #106, #'A'
	static tile_map_og + #107, #0
	static tile_map_og + #108, #0
	static tile_map_og + #109, #'A'
	static tile_map_og + #110, #'B'
	static tile_map_og + #111, #'B'
	static tile_map_og + #112, #0
	static tile_map_og + #113, #0
	static tile_map_og + #114, #'B'
	static tile_map_og + #115, #'A'
	static tile_map_og + #116, #'B'
	static tile_map_og + #117, #'A'
	static tile_map_og + #118, #'B'
	static tile_map_og + #119, #'A'
	static tile_map_og + #120, #'A'
	static tile_map_og + #121, #'B'
	static tile_map_og + #122, #'B'
	static tile_map_og + #123, #'B'
	static tile_map_og + #124, #'B'
	static tile_map_og + #125, #'B'
	static tile_map_og + #126, #0
	static tile_map_og + #127, #'B'
	static tile_map_og + #128, #'B'
	static tile_map_og + #129, #'A'
	static tile_map_og + #130, #'B'
	static tile_map_og + #131, #'B'
	static tile_map_og + #132, #0
	static tile_map_og + #133, #0
	static tile_map_og + #134, #'B'
	static tile_map_og + #135, #0
	static tile_map_og + #136, #'B'
	static tile_map_og + #137, #'B'
	static tile_map_og + #138, #'B'
	static tile_map_og + #139, #'A'
	static tile_map_og + #140, #'A'
	static tile_map_og + #141, #'B'
	static tile_map_og + #142, #'A'
	static tile_map_og + #143, #'B'
	static tile_map_og + #144, #'A'
	static tile_map_og + #145, #'B'
	static tile_map_og + #146, #0
	static tile_map_og + #147, #'B'
	static tile_map_og + #148, #'B'
	static tile_map_og + #149, #'A'
	static tile_map_og + #150, #0
	static tile_map_og + #151, #0
	static tile_map_og + #152, #'A'
	static tile_map_og + #153, #'A'
	static tile_map_og + #154, #'A'
	static tile_map_og + #155, #'A'
	static tile_map_og + #156, #'B'
	static tile_map_og + #157, #'B'
	static tile_map_og + #158, #'B'
	static tile_map_og + #159, #'A'
	static tile_map_og + #160, #'A'
	static tile_map_og + #161, #'B'
	static tile_map_og + #162, #'B'
	static tile_map_og + #163, #'B'
	static tile_map_og + #164, #'B'
	static tile_map_og + #165, #'B'
	static tile_map_og + #166, #0
	static tile_map_og + #167, #'B'
	static tile_map_og + #168, #'B'
	static tile_map_og + #169, #'A'
	static tile_map_og + #170, #0
	static tile_map_og + #171, #0
	static tile_map_og + #172, #'A'
	static tile_map_og + #173, #0
	static tile_map_og + #174, #0
	static tile_map_og + #175, #0
	static tile_map_og + #176, #0
	static tile_map_og + #177, #0
	static tile_map_og + #178, #0
	static tile_map_og + #179, #'A'
	static tile_map_og + #180, #'A'
	static tile_map_og + #181, #'B'
	static tile_map_og + #182, #'A'
	static tile_map_og + #183, #'B'
	static tile_map_og + #184, #'A'
	static tile_map_og + #185, #'B'
	static tile_map_og + #186, #0
	static tile_map_og + #187, #'B'
	static tile_map_og + #188, #'B'
	static tile_map_og + #189, #'A'
	static tile_map_og + #190, #'B'
	static tile_map_og + #191, #'B'
	static tile_map_og + #192, #'A'
	static tile_map_og + #193, #0
	static tile_map_og + #194, #'B'
	static tile_map_og + #195, #0
	static tile_map_og + #196, #0
	static tile_map_og + #197, #0
	static tile_map_og + #198, #0
	static tile_map_og + #199, #'A'
	static tile_map_og + #200, #'A'
	static tile_map_og + #201, #'B'
	static tile_map_og + #202, #'B'
	static tile_map_og + #203, #'B'
	static tile_map_og + #204, #'B'
	static tile_map_og + #205, #'B'
	static tile_map_og + #206, #'A'
	static tile_map_og + #207, #0
	static tile_map_og + #208, #0
	static tile_map_og + #209, #0
	static tile_map_og + #210, #0
	static tile_map_og + #211, #0
	static tile_map_og + #212, #'B'
	static tile_map_og + #213, #0
	static tile_map_og + #214, #0
	static tile_map_og + #215, #0
	static tile_map_og + #216, #0
	static tile_map_og + #217, #0
	static tile_map_og + #218, #0
	static tile_map_og + #219, #'A'
	static tile_map_og + #220, #'A'
	static tile_map_og + #221, #0
	static tile_map_og + #222, #0
	static tile_map_og + #223, #0
	static tile_map_og + #224, #0
	static tile_map_og + #225, #0
	static tile_map_og + #226, #0
	static tile_map_og + #227, #0
	static tile_map_og + #228, #0
	static tile_map_og + #229, #'A'
	static tile_map_og + #230, #0
	static tile_map_og + #231, #0
	static tile_map_og + #232, #'B'
	static tile_map_og + #233, #0
	static tile_map_og + #234, #0
	static tile_map_og + #235, #0
	static tile_map_og + #236, #0
	static tile_map_og + #237, #0
	static tile_map_og + #238, #0
	static tile_map_og + #239, #'A'
	static tile_map_og + #240, #'A'
	static tile_map_og + #241, #'A'
	static tile_map_og + #242, #'A'
	static tile_map_og + #243, #'A'
	static tile_map_og + #244, #'A'
	static tile_map_og + #245, #'A'
	static tile_map_og + #246, #'A'
	static tile_map_og + #247, #'A'
	static tile_map_og + #248, #'A'
	static tile_map_og + #249, #'A'
	static tile_map_og + #250, #'A'
	static tile_map_og + #251, #'A'
	static tile_map_og + #252, #'A'
	static tile_map_og + #253, #'A'
	static tile_map_og + #254, #'A'
	static tile_map_og + #255, #'A'
	static tile_map_og + #256, #'A'
	static tile_map_og + #257, #'A'
	static tile_map_og + #258, #'A'
	static tile_map_og + #259, #'A'
